### ISSUE TITLE
Couldn't resolve native function 'opencc_open'

### ISSUE THREAD

**Issue by zeqinjie** [lindeer/opencc-dart#3]
你好我使用这个库，我遇到错误如下
Invalid argument(s): Couldn't resolve native function 'opencc_open' in 'package:opencc/src/lib_opencc.dart' : No asset with id 'package:opencc/src/lib_opencc.dart' found. No available native assets. Attempted to fallback to process lookup. dlsym(RTLD_DEFAULT, opencc_open): symbol not found.

**Comment by lindeer** [comment]
@zeqinjie 你好，opencc作为直接可运行文件目前native-assest还不支持，windows下编译因为msys的原因也有这个错误，能把你的情况说的再详尽些么？

**Comment by zeqinjie** [comment]
@lindeer 你好，我安装文档说明先执行了 `dart --enable-experiment=native-assets run bin/opencc.dart.`  后执行脚本还是会报上面的错误。

**Comment by lindeer** [comment]
@zeqinjie 这是因为native-assets不支持直接`dart run` 看[这里](https://github.com/dart-lang/sdk/issues/56044)
